#ifndef METER_ENUM_H
#define METER_ENUM_H

enum METER_TYPE
{
    METER_NOT_SET = 0,
    //bus
    METER_BUS_VOLTAGE_IN_PU = 101,
    METER_BUS_VOLTAGE_IN_KV = 102,
    METER_BUS_ANGLE_IN_DEG = 103,
    METER_BUS_ANGLE_IN_RAD = 104,
    METER_BUS_FREQUENCY_IN_PU = 105,
    METER_BUS_FREQUENCY_IN_HZ = 106,
    METER_BUS_FREQUENCY_DEVIATION_IN_PU = 107,
    METER_BUS_FREQUENCY_DEVIATION_IN_HZ = 108,
    METER_BUS_ROCOV_IN_PU_PER_S = 109,
    METER_BUS_ROCOV_IN_KV_PER_S = 110,
    METER_BUS_ROCOF_IN_PU_PER_S = 111,
    METER_BUS_ROCOF_IN_HZ_PER_S = 112,

    // line
    METER_LINE_CURRENT_AT_SENDING_SIDE_IN_KA = 201,
    METER_LINE_CURRENT_AT_RECEIVING_SIDE_IN_KA = 202,
    METER_LINE_ACTIVE_POWER_AT_SENDING_SIDE_IN_MW = 203,
    METER_LINE_ACTIVE_POWER_AT_RECEIVING_SIDE_IN_MW = 204,
    METER_LINE_REACTIVE_POWER_AT_SENDING_SIDE_IN_MVAR = 205,
    METER_LINE_REACTIVE_POWER_AT_RECEIVING_SIDE_IN_MVAR = 206,
    METER_LINE_APPARENT_IMPEDANCE_AT_SENDING_SIDE_IN_OHM = 207,
    METER_LINE_APPARENT_IMPEDANCE_AT_RECEIVING_SIDE_IN_OHM = 208,
    METER_LINE_APPARENT_IMPEDANCE_ANGLE_AT_SENDING_SIDE_IN_DEG = 209,
    METER_LINE_APPARENT_IMPEDANCE_ANGLE_AT_RECEIVING_SIDE_IN_DEG = 210,

    // transformer
    METER_TRANSFORMER_CURRENT_AT_PRIMARY_WINDING_IN_KA = 301,
    METER_TRANSFORMER_CURRENT_AT_SECONDARY_WINDING_IN_KA = 302,
    METER_TRANSFORMER_CURRENT_AT_TERTIARY_WINDING_IN_KA = 303,
    METER_TRANSFORMER_ACTIVE_POWER_AT_PRIMARY_WINDING_IN_MW = 304,
    METER_TRANSFORMER_ACTIVE_POWER_AT_SECONDARY_WINDING_IN_MW = 305,
    METER_TRANSFORMER_ACTIVE_POWER_AT_TERTIARY_WINDING_IN_MW = 306,
    METER_TRANSFORMER_REACTIVE_POWER_AT_PRIMARY_WINDING_IN_MVAR = 307,
    METER_TRANSFORMER_REACTIVE_POWER_AT_SECONDARY_WINDING_IN_MVAR = 308,
    METER_TRANSFORMER_REACTIVE_POWER_AT_TERTIARY_WINDING_IN_MVAR = 309,
    METER_TRANSFORMER_EXCITATION_VOLTAGE_IN_PU = 310,

    // sync generator
    METER_GENERATOR_ROTOR_ANGLE_IN_DEG = 401,
    METER_GENERATOR_ROTOR_SPEED_IN_PU = 402,
    METER_GENERATOR_ROTOR_SPEED_IN_HZ = 403,
    METER_GENERATOR_ROTOR_SPEED_DEVIATION_IN_PU = 404,
    METER_GENERATOR_ROTOR_SPEED_DEVIATION_IN_HZ = 405,
    METER_GENERATOR_INTERNAL_VOLTAGE_IN_PU = 406,
    METER_GENERATOR_TERMINAL_CURRENT_IN_PU = 407,
    METER_GENERATOR_TERMINAL_CURRENT_IN_KA = 408,
    METER_GENERATOR_TERMINAL_ACTIVE_POWER_IN_MW = 409,
    METER_GENERATOR_TERMINAL_ACTIVE_POWER_IN_PU = 410,
    METER_GENERATOR_TERMINAL_REACTIVE_POWER_IN_MVAR = 411,
    METER_GENERATOR_TERMINAL_REACTIVE_POWER_IN_PU = 412,
    METER_GENERATOR_AIRGAP_POWER_IN_MW = 413,
    METER_GENERATOR_AIRGAP_POWER_IN_PU = 414,
    METER_GENERATOR_ACCELERATING_POWER_IN_PU = 415,
    METER_GENERATOR_ACCELERATING_POWER_IN_MW = 416,
    METER_GENERATOR_MECHANICAL_POWER_IN_MW = 417,
    METER_GENERATOR_MECHANICAL_POWER_IN_PU = 418,
    METER_GENERATOR_EXCITATION_VOLTAGE_IN_PU = 419,
    METER_GENERATOR_STABILIZING_SIGNAL_IN_PU = 420,
    METER_GENERATOR_COMPENSATING_VOLTAGE_IN_PU = 421,
    METER_GENERATOR_SYNC_GENERATOR_MODEL_INTERNAL_VARIABLE = 422,
    METER_GENERATOR_COMPENSATOR_MODEL_INTERNAL_VARIABLE = 423,
    METER_GENERATOR_EXCITER_MODEL_INTERNAL_VARIABLE = 424,
    METER_GENERATOR_STABILIZER_MODEL_INTERNAL_VARIABLE = 425,
    METER_GENERATOR_TURBINE_GOVERNOR_MODEL_INTERNAL_VARIABLE = 426,

    // load
    METER_LOAD_ACTIVE_POWER_IN_MW = 501,
    METER_LOAD_REACTIVE_POWER_IN_MVAR = 502,
    METER_LOAD_CURRENT_IN_KA = 503,
    METER_LOAD_LOAD_MODEL_INTERNAL_VARIABLE = 504,
    METER_LOAD_FREQUENCY_RELAY_MODEL_INTERNAL_VARIABLE = 505,
    METER_LOAD_VOLTAGE_RELAY_MODEL_INTERNAL_VARIABLE = 506,

    // hvdc
    METER_HVDC_RECTIFIER_DC_CURRENT_IN_KA = 601,
    METER_HVDC_INVERTER_DC_CURRENT_IN_KA = 602,
    METER_HVDC_RCTIFIER_DC_VOLTAGE_IN_KV = 603,
    METER_HVDC_INVERTER_DC_VOLTAGE_IN_KV = 604,
    METER_HVDC_RECTIFIER_DC_POWER_IN_MW = 605,
    METER_HVDC_INVERTER_DC_POWER_IN_MW = 606,
    METER_HVDC_RECTIFIER_AC_ACTIVE_POWER_IN_MW = 607,
    METER_HVDC_INVERTER_AC_ACTIVE_POWER_IN_MW = 608,
    METER_HVDC_RECTIFIER_AC_REACTIVE_POWER_IN_MVAR = 609,
    METER_HVDC_INVERTER_AC_REACTIVE_POWER_IN_MVAR = 610,
    METER_HVDC_RECTIFIER_ALPHA_IN_DEG = 611,
    METER_HVDC_INVERTER_GAMMA_IN_DEG = 612,
    METER_HVDC_RECTIFIER_MU_IN_DEG = 613,
    METER_HVDC_INVERTER_MU_IN_DEG = 614,
    METER_HVDC_HVDC_MODEL_INTERNAL_VARIABLE = 615,

    // wind turbine generator
    METER_WIND_TURBINE_GENERATOR_ROTOR_SPEED_IN_PU = 701,
    METER_WIND_TURBINE_GENERATOR_ROTOR_SPEED_IN_HZ = 702,
    METER_WIND_TURBINE_GENERATOR_ROTOR_SPEED_DEVIATION_IN_PU = 703,
    METER_WIND_TURBINE_GENERATOR_ROTOR_SPEED_DEVIATION_IN_HZ = 704,
    METER_WIND_TURBINE_GENERATOR_TREMINAL_CURRENT_IN_KA = 705,
    METER_WIND_TURBINE_GENERATOR_TERMIANL_ACTIVE_POWER_IN_MW = 706,
    METER_WIND_TURBINE_GENERATOR_TERMIANL_REACTIVE_POWER_IN_MVAR = 707,
    METER_WIND_TURBINE_GENERATOR_MECHANICAL_POWER_IN_MW = 708,
    METER_WIND_TURBINE_GENERATOR_PITCH_ANGLE_IN_DEG = 709,
    METER_WIND_TURBINE_GENERATOR_WT_GENERATOR_MODEL_INTERNAL_VARIABLE = 710,
    METER_WIND_TURBINE_GENERATOR_ELECTRICAL_CONTROL_MODEL_INTERNAL_VARIABLE = 711,
    METER_WIND_TURBINE_GENERATOR_MECHANICAL_MODEL_INTERNAL_VARIABLE = 712,
    METER_WIND_TURBINE_GENERATOR_PITCH_CONTROL_MODEL_INTERNAL_VARIABLE = 713,

    //equivalent device
    METER_EQUIVALENT_DEVICE_VOLTAGE_SOURCE_VOLTAGE_IN_PU = 9901,
    METER_EQUIVALENT_DEVICE_VOLTAGE_SOURCE_VOLTAGE_ANGLE_IN_DEG = 9902,
    METER_EQUIVALENT_DEVICE_VOLTAGE_SOURCE_RESISTANCE_IN_PU = 9903,
    METER_EQUIVALENT_DEVICE_VOLTAGE_SOURCE_REACTANCE_IN_PU = 9904,
    METER_EQUIVALENT_DEVICE_ACTIVE_CONSTANT_POWER_LOAD_IN_MW = 9905,
    METER_EQUIVALENT_DEVICE_REACTIVE_CONSTANT_POWER_LOAD_IN_MVAR = 9906,
    METER_EQUIVALENT_DEVICE_ACTIVE_CONSTANT_CURRENT_LOAD_IN_MW = 9907,
    METER_EQUIVALENT_DEVICE_REACTIVE_CONSTANT_CURRENT_LOAD_IN_MVAR = 9908,
    METER_EQUIVALENT_DEVICE_ACTIVE_CONSTANT_IMPEDANCE_LOAD_IN_MW = 9909,
    METER_EQUIVALENT_DEVICE_REACTIVE_CONSTANT_IMPEDANCE_LOAD_IN_MVAR = 9910
};


#endif // METER_ENUM_H
