from pysteps import libsteps as ls


ls.api_initialize_package()


ls.api_set_package_float_data('fbase', 60)
ls.api_set_package_float_data('sbase', 100)

ls.api_add_bus(1,'BUS1',16.5)
ls.api_set_bus_integer_data(1,'type',3)
ls.api_set_bus_float_data(1,'V_PU',1)
ls.api_set_bus_float_data(1,'ANGLE_DEG',0.0)
ls.api_add_bus(2,'BUS2',18.0)
ls.api_set_bus_integer_data(2,'type',2)
ls.api_set_bus_float_data(2,'V_PU',1)
ls.api_set_bus_float_data(2,'ANGLE_DEG',0.0)
ls.api_add_bus(3,'BUS3',13.8)
ls.api_set_bus_integer_data(3,'type',2)
ls.api_set_bus_float_data(3,'V_PU',1)
ls.api_set_bus_float_data(3,'ANGLE_DEG',0.0)
ls.api_add_bus(4,'BUS4',230.0)
ls.api_set_bus_integer_data(4,'type',1)
ls.api_set_bus_float_data(4,'V_PU',1)
ls.api_set_bus_float_data(4,'ANGLE_DEG',0.0)
ls.api_add_bus(5,'BUS5',230.0)
ls.api_set_bus_integer_data(5,'type',1)
ls.api_set_bus_float_data(5,'V_PU',1)
ls.api_set_bus_float_data(5,'ANGLE_DEG',0.0)
ls.api_add_bus(6,'BUS6',230.0)
ls.api_set_bus_integer_data(6,'type',1)
ls.api_set_bus_float_data(6,'V_PU',1)
ls.api_set_bus_float_data(6,'ANGLE_DEG',0.0)
ls.api_add_bus(7,'BUS7',230.0)
ls.api_set_bus_integer_data(7,'type',1)
ls.api_set_bus_float_data(7,'V_PU',1)
ls.api_set_bus_float_data(7,'ANGLE_DEG',0.0)
ls.api_add_bus(8,'BUS8',230.0)
ls.api_set_bus_integer_data(8,'type',1)
ls.api_set_bus_float_data(8,'V_PU',1)
ls.api_set_bus_float_data(8,'ANGLE_DEG',0.0)
ls.api_add_bus(9,'BUS9',230.0)
ls.api_set_bus_integer_data(9,'type',1)
ls.api_set_bus_float_data(9,'V_PU',1)
ls.api_set_bus_float_data(9,'ANGLE_DEG',0.0)


ls.api_add_generator(1,'G1')
ls.api_set_source_boolean_data(1,'G1','STATUS',True)
ls.api_set_source_integer_data(1,'G1','BUS_REG',1)
ls.api_set_source_integer_data(1,'G1','MODE',3)
ls.api_set_source_float_data(1,'G1','MBASE_MVA',100.0)
ls.api_set_source_float_data(1,'G1','QMAX_MVAR',999.0)
ls.api_set_source_float_data(1,'G1','QMIN_MVAR',-999.0)
ls.api_set_source_float_data(1,'G1','VREG_PU',1.040)
ls.api_set_source_float_data(1,'G1','RSOURCE_PU',0.0)
ls.api_set_source_float_data(1,'G1','XSOURCE_PU',0.1460)
ls.api_add_generator(2,'G2')
ls.api_set_source_boolean_data(2,'G2','STATUS',True)
ls.api_set_source_integer_data(2,'G2','BUS_REG',2)
ls.api_set_source_integer_data(2,'G2','MODE',2)
ls.api_set_source_float_data(2,'G2','MBASE_MVA',100.0)
ls.api_set_source_float_data(2,'G2','PGEN_MW',163.0)
ls.api_set_source_float_data(2,'G2','QMAX_MVAR',999.0)
ls.api_set_source_float_data(2,'G2','QMIN_MVAR',-999.0)
ls.api_set_source_float_data(2,'G2','VREG_PU',1.025)
ls.api_set_source_float_data(2,'G2','RSOURCE_PU',0.0)
ls.api_set_source_float_data(2,'G2','XSOURCE_PU',0.8958)
ls.api_add_generator(3,'G3')
ls.api_set_source_boolean_data(3,'G3','STATUS',True)
ls.api_set_source_integer_data(3,'G3','BUS_REG',3)
ls.api_set_source_integer_data(3,'G3','MODE',2)
ls.api_set_source_float_data(3,'G3','MBASE_MVA',100.0)
ls.api_set_source_float_data(3,'G3','PGEN_MW',85.0)
ls.api_set_source_float_data(3,'G3','QMAX_MVAR',999.0)
ls.api_set_source_float_data(3,'G3','QMIN_MVAR',-999.0)
ls.api_set_source_float_data(3,'G3','VREG_PU',1.025)
ls.api_set_source_float_data(3,'G3','RSOURCE_PU',0.0)
ls.api_set_source_float_data(3,'G3','XSOURCE_PU',1.3125)



ls.api_add_load(5,'LOAD1')
ls.api_set_load_boolean_data(5,'LOAD1','STATUS',True)
ls.api_set_load_float_data(5,'LOAD1','PP0_MW',125.0)
ls.api_set_load_float_data(5,'LOAD1','QP0_MVAR',50.0)
ls.api_add_load(6,'LOAD2')
ls.api_set_load_boolean_data(6,'LOAD2','STATUS',True)
ls.api_set_load_float_data(6,'LOAD2','PP0_MW',90.0)
ls.api_set_load_float_data(6,'LOAD2','QP0_MVAR',30.0)
ls.api_add_load(8,'LOAD3')
ls.api_set_load_boolean_data(8,'LOAD3','STATUS',True)
ls.api_set_load_float_data(8,'LOAD3','PP0_MW',100.0)
ls.api_set_load_float_data(8,'LOAD3','QP0_MVAR',35.0)


ls.api_add_line(4,5,'LINE1')
ls.api_set_line_boolean_data(4,5,'LINE1','STATUS_SEND',True)
ls.api_set_line_boolean_data(4,5,'LINE1','STATUS_RECV',True)
ls.api_set_line_float_data(4,5,'LINE1','R1_PU',0.010)
ls.api_set_line_float_data(4,5,'LINE1','X1_PU',0.085)
ls.api_set_line_float_data(4,5,'LINE1','G1_PU',0.0)
ls.api_set_line_float_data(4,5,'LINE1','B1_PU',0.176)
ls.api_add_line(4,6,'LINE2')
ls.api_set_line_boolean_data(4,6,'LINE2','STATUS_SEND',True)
ls.api_set_line_boolean_data(4,6,'LINE2','STATUS_RECV',True)
ls.api_set_line_float_data(4,6,'LINE2','R1_PU',0.017)
ls.api_set_line_float_data(4,6,'LINE2','X1_PU',0.092)
ls.api_set_line_float_data(4,6,'LINE2','G1_PU',0.0)
ls.api_set_line_float_data(4,6,'LINE2','B1_PU',0.158)
ls.api_add_line(5,7,'LINE3')
ls.api_set_line_boolean_data(5,7,'LINE3','STATUS_SEND',True)
ls.api_set_line_boolean_data(5,7,'LINE3','STATUS_RECV',True)
ls.api_set_line_float_data(5,7,'LINE3','R1_PU',0.032)
ls.api_set_line_float_data(5,7,'LINE3','X1_PU',0.161)
ls.api_set_line_float_data(5,7,'LINE3','G1_PU',0.0)
ls.api_set_line_float_data(5,7,'LINE3','B1_PU',0.306)
ls.api_add_line(6,9,'LINE4')
ls.api_set_line_boolean_data(6,9,'LINE4','STATUS_SEND',True)
ls.api_set_line_boolean_data(6,9,'LINE4','STATUS_RECV',True)
ls.api_set_line_float_data(6,9,'LINE4','R1_PU',0.039)
ls.api_set_line_float_data(6,9,'LINE4','X1_PU',0.170)
ls.api_set_line_float_data(6,9,'LINE4','G1_PU',0.0)
ls.api_set_line_float_data(6,9,'LINE4','B1_PU',0.358)
ls.api_add_line(7,8,'LINE5')
ls.api_set_line_boolean_data(7,8,'LINE5','STATUS_SEND',True)
ls.api_set_line_boolean_data(7,8,'LINE5','STATUS_RECV',True)
ls.api_set_line_float_data(7,8,'LINE5','R1_PU',0.0085)
ls.api_set_line_float_data(7,8,'LINE5','X1_PU',0.072)
ls.api_set_line_float_data(7,8,'LINE5','G1_PU',0.0)
ls.api_set_line_float_data(7,8,'LINE5','B1_PU',0.149)
ls.api_add_line(8,9,'LINE6')
ls.api_set_line_boolean_data(8,9,'LINE6','STATUS_SEND',True)
ls.api_set_line_boolean_data(8,9,'LINE6','STATUS_RECV',True)
ls.api_set_line_float_data(8,9,'LINE6','R1_PU',0.0119)
ls.api_set_line_float_data(8,9,'LINE6','X1_PU',0.1008)
ls.api_set_line_float_data(8,9,'LINE6','G1_PU',0.0)
ls.api_set_line_float_data(8,9,'LINE6','B1_PU',0.209)


ls.api_add_transformer(1,4,0,'TRA1')
ls.api_set_transformer_float_data(1,4,0,'TRA1','PRIMARY','VN_KV',16.5)
ls.api_set_transformer_float_data(1,4,0,'TRA1','SECONDARY','VN_KV',230.0)
ls.api_set_transformer_boolean_data(1,4,0,'TRA1','PRIMARY','STATUS',True)
ls.api_set_transformer_boolean_data(1,4,0,'TRA1','SECONDARY','STATUS',True)
ls.api_set_transformer_float_data(1,4,0,'TRA1','TRANSFORMER','SBASE_PS_MVA',100.0)
ls.api_set_transformer_float_data(1,4,0,'TRA1','TRANSFORMER','GM_PU',0.0)
ls.api_set_transformer_float_data(1,4,0,'TRA1','TRANSFORMER','BM_PU',0.0)
ls.api_set_transformer_float_data(1,4,0,'TRA1','TRANSFORMER','R_PS_PU',0.0)
ls.api_set_transformer_float_data(1,4,0,'TRA1','TRANSFORMER','X_PS_PU',0.0576)
ls.api_add_transformer(2,7,0,'TRA2')
ls.api_set_transformer_float_data(2,7,0,'TRA2','PRIMARY','VN_KV',18)
ls.api_set_transformer_float_data(2,7,0,'TRA2','SECONDARY','VN_KV',230.0)
ls.api_set_transformer_boolean_data(2,7,0,'TRA2','PRIMARY','STATUS',True)
ls.api_set_transformer_boolean_data(2,7,0,'TRA2','SECONDARY','STATUS',True)
ls.api_set_transformer_float_data(2,7,0,'TRA2','TRANSFORMER','SBASE_PS_MVA',100.0)
ls.api_set_transformer_float_data(2,7,0,'TRA2','TRANSFORMER','GM_PU',0.0)
ls.api_set_transformer_float_data(2,7,0,'TRA2','TRANSFORMER','BM_PU',0.0)
ls.api_set_transformer_float_data(2,7,0,'TRA2','TRANSFORMER','R_PS_PU',0.0)
ls.api_set_transformer_float_data(2,7,0,'TRA2','TRANSFORMER','X_PS_PU',0.0625)
ls.api_add_transformer(3,9,0,'TRA3')
ls.api_set_transformer_float_data(3,9,0,'TRA3','PRIMARY','VN_KV',13.8)
ls.api_set_transformer_float_data(3,9,0,'TRA3','SECONDARY','VN_KV',230.0)
ls.api_set_transformer_boolean_data(3,9,0,'TRA3','PRIMARY','STATUS',True)
ls.api_set_transformer_boolean_data(3,9,0,'TRA3','SECONDARY','STATUS',True)
ls.api_set_transformer_float_data(3,9,0,'TRA3','TRANSFORMER','SBASE_PS_MVA',100.0)
ls.api_set_transformer_float_data(3,9,0,'TRA3','TRANSFORMER','GM_PU',0.0)
ls.api_set_transformer_float_data(3,9,0,'TRA3','TRANSFORMER','BM_PU',0.0)
ls.api_set_transformer_float_data(3,9,0,'TRA3','TRANSFORMER','R_PS_PU',0.0)
ls.api_set_transformer_float_data(3,9,0,'TRA3','TRANSFORMER','X_PS_PU',0.0586)


ls.api_show_device_data("ALL")

ls.api_initialize_powerflow_solver()

ls.api_set_powerflow_solver_boolean_parameter("Flat start logic", True)
ls.api_set_powerflow_solver_float_parameter("max active power imbalance in MW", 0.01)
ls.api_set_powerflow_solver_float_parameter("max reactive power imbalance in MVar", 0.01)

ls.api_solve_powerflow("NR")


ls.api_is_powerflow_converged()


ls.api_show_powerflow_result()





